### ISSUE TITLE
Bro,what's the difference between the `rank` and `local_rank`?

### ISSUE THREAD

**Issue by buaacarzp** [BIGBALLON/distribuuuu#16]
https://github.com/BIGBALLON/distribuuuu/blob/c8c17dca6698145945a19c692a5fc191f758b1ed/tutorial/mnmc_ddp_launch.py#L23-L24

**Comment by BIGBALLON** [comment]
- Reference: 

1. https://pytorch.org/tutorials/beginner/dist_overview.html
2. https://github.com/pytorch/examples/blob/master/distributed/ddp/README.md
3. https://zhuanlan.zhihu.com/p/360405558

- Explanation

Assume you have **4** machines with **32** GPUs (8GPUs **per** machine)

- ``world_size`` is **32** 
- ``rank``  are **0 ~ 31**
- ``local_rank`` are **0 ~ 7**, since one machine has only 8 GPUs, so you need use the device number **0 ~ 7**

https://github.com/BIGBALLON/distribuuuu/blob/c8c17dca6698145945a19c692a5fc191f758b1ed/tutorial/mnmc_ddp_launch.py#L35





I suggest you read [dist_overview](https://pytorch.org/tutorials/beginner/dist_overview.html) first.

**Comment by buaacarzp** [comment]
> * Reference:
> 
> 1. https://pytorch.org/tutorials/beginner/dist_overview.html
> 2. https://github.com/pytorch/examples/blob/master/distributed/ddp/README.md
> 3. https://zhuanlan.zhihu.com/p/360405558
> 
> * Explanation
> 
> Assume you have **4** machines with **32** GPUs (8GPUs **per** machine)
> 
> * `world_size` is **32**
> * `rank`  are **0 ~ 31**
> * `local_rank` are **0 ~ 7**, since one machine have only 8 GPUs, so you need use the device number **0 ~ 7**
> 
> https://github.com/BIGBALLON/distribuuuu/blob/c8c17dca6698145945a19c692a5fc191f758b1ed/tutorial/mnmc_ddp_launch.py#L35
> 
> I suggest you read [dist_overview](https://pytorch.org/tutorials/beginner/dist_overview.html) first.

goog job, I like you very much !
